---
all:
  children:
    <VM_Location>: # Can be where the VM is stored eg. dmz, lan etc.
      hosts:
        <VM_name>: # VM name in VSphere/VMWare
          ansible_host: <VM_IP> # VM IP assigned to the VM name above